package b.nana.technology.gingester.transformers.base;

import b.nana.technology.gingester.core.provider.Provider;
import b.nana.technology.gingester.core.transformer.Transformer;

import java.util.Collection;
import java.util.List;
import java.util.Map;

public final class BaseProvider implements Provider {

    @Override
    public Map<String, String> getCaseHints() {
        return Map.of(
                "bigdecimal", "BigDecimal",
                "groupby", "GroupBy",
                "inputstream", "InputStream",
                "outputstream", "OutputStream"
        );
    }

    @Override
    public Collection<Class<? extends Transformer<?, ?>>> getTransformerClasses() {
        return List.of(
                b.nana.technology.gingester.transformers.base.transformers.base16.Encode.class,
                b.nana.technology.gingester.transformers.base.transformers.base64.Encode.class,
                b.nana.technology.gingester.transformers.base.transformers.bigdecimal.Multiply.class,
                b.nana.technology.gingester.transformers.base.transformers.bytes.FilterEmptyOut.class,
                b.nana.technology.gingester.transformers.base.transformers.bytes.FromOutputStream.class,
                b.nana.technology.gingester.transformers.base.transformers.bytes.ToInputStream.class,
                b.nana.technology.gingester.transformers.base.transformers.bytes.ToJson.class,
                b.nana.technology.gingester.transformers.base.transformers.bytes.ToString.class,
                b.nana.technology.gingester.transformers.base.transformers.cron.Job.class,
                b.nana.technology.gingester.transformers.base.transformers.dsv.FromJson.class,
                b.nana.technology.gingester.transformers.base.transformers.dsv.ToJson.class,
                b.nana.technology.gingester.transformers.base.transformers.exec.Exec.class,
                b.nana.technology.gingester.transformers.base.transformers.groupby.BytesLimit.class,
                b.nana.technology.gingester.transformers.base.transformers.groupby.CountLimit.class,
                b.nana.technology.gingester.transformers.base.transformers.groupby.CountModulo.class,
                b.nana.technology.gingester.transformers.base.transformers.groupby.Equals.class,
                b.nana.technology.gingester.transformers.base.transformers.groupby.TimeInterval.class,
                b.nana.technology.gingester.transformers.base.transformers.hash.Sha1.class,
                b.nana.technology.gingester.transformers.base.transformers.html.ElementsContainingOwnText.class,
                b.nana.technology.gingester.transformers.base.transformers.html.ElementsContainingText.class,
                b.nana.technology.gingester.transformers.base.transformers.html.FromString.class,
                b.nana.technology.gingester.transformers.base.transformers.html.NextElementSibling.class,
                b.nana.technology.gingester.transformers.base.transformers.html.Select.class,
                b.nana.technology.gingester.transformers.base.transformers.html.ToString.class,
                b.nana.technology.gingester.transformers.base.transformers.http.Http.class,
                b.nana.technology.gingester.transformers.base.transformers.http.ToFormData.class,
                b.nana.technology.gingester.transformers.base.transformers.inputstream.Append.class,
                b.nana.technology.gingester.transformers.base.transformers.inputstream.Drain.class,
                b.nana.technology.gingester.transformers.base.transformers.inputstream.FromOutputStream.class,
                b.nana.technology.gingester.transformers.base.transformers.inputstream.Gunzip.class,
                b.nana.technology.gingester.transformers.base.transformers.inputstream.Join.class,
                b.nana.technology.gingester.transformers.base.transformers.inputstream.PeekBytes.class,
                b.nana.technology.gingester.transformers.base.transformers.inputstream.PeekLines.class,
                b.nana.technology.gingester.transformers.base.transformers.inputstream.PeekString.class,
                b.nana.technology.gingester.transformers.base.transformers.inputstream.Pipe.class,
                b.nana.technology.gingester.transformers.base.transformers.inputstream.Prepend.class,
                b.nana.technology.gingester.transformers.base.transformers.inputstream.Skip.class,
                b.nana.technology.gingester.transformers.base.transformers.inputstream.Split.class,
                b.nana.technology.gingester.transformers.base.transformers.inputstream.ToLines.class,
                b.nana.technology.gingester.transformers.base.transformers.inputstream.ToBytes.class,
                b.nana.technology.gingester.transformers.base.transformers.inputstream.ToJson.class,
                b.nana.technology.gingester.transformers.base.transformers.inputstream.ToOutputStream.class,
                b.nana.technology.gingester.transformers.base.transformers.inputstream.ToString.class,
                b.nana.technology.gingester.transformers.base.transformers.join.OuterJoin.class,
                b.nana.technology.gingester.transformers.base.transformers.json.Add.class,
                b.nana.technology.gingester.transformers.base.transformers.json.AsBigDecimal.class,
                b.nana.technology.gingester.transformers.base.transformers.json.AsBoolean.class,
                b.nana.technology.gingester.transformers.base.transformers.json.AsDouble.class,
                b.nana.technology.gingester.transformers.base.transformers.json.AsFloat.class,
                b.nana.technology.gingester.transformers.base.transformers.json.AsInteger.class,
                b.nana.technology.gingester.transformers.base.transformers.json.AsLong.class,
                b.nana.technology.gingester.transformers.base.transformers.json.AsText.class,
                b.nana.technology.gingester.transformers.base.transformers.json.CamelCase.class,
                b.nana.technology.gingester.transformers.base.transformers.json.Copy.class,
                b.nana.technology.gingester.transformers.base.transformers.json.Def.class,
                b.nana.technology.gingester.transformers.base.transformers.json.ForceArrays.class,
                b.nana.technology.gingester.transformers.base.transformers.json.Flatten.class,
                b.nana.technology.gingester.transformers.base.transformers.json.Internpret.class,
                b.nana.technology.gingester.transformers.base.transformers.json.ObjectToArray.class,
                b.nana.technology.gingester.transformers.base.transformers.json.Path.class,
                b.nana.technology.gingester.transformers.base.transformers.json.Remove.class,
                b.nana.technology.gingester.transformers.base.transformers.json.ReplaceBytesWithPaths.class,
                b.nana.technology.gingester.transformers.base.transformers.json.Set.class,
                b.nana.technology.gingester.transformers.base.transformers.json.SnakeCase.class,
                b.nana.technology.gingester.transformers.base.transformers.json.Stream.class,
                b.nana.technology.gingester.transformers.base.transformers.json.TextValues.class,
                b.nana.technology.gingester.transformers.base.transformers.json.ToString.class,
                b.nana.technology.gingester.transformers.base.transformers.json.Trim.class,
                b.nana.technology.gingester.transformers.base.transformers.json.Wrap.class,
                b.nana.technology.gingester.transformers.base.transformers.list.Collect.class,
                b.nana.technology.gingester.transformers.base.transformers.list.Stream.class,
                b.nana.technology.gingester.transformers.base.transformers.map.Collect.class,
                b.nana.technology.gingester.transformers.base.transformers.map.CollectCounts.class,
                b.nana.technology.gingester.transformers.base.transformers.map.CollectLists.class,
                b.nana.technology.gingester.transformers.base.transformers.map.CollectSets.class,
                b.nana.technology.gingester.transformers.base.transformers.map.Get.class,
                b.nana.technology.gingester.transformers.base.transformers.map.GetNullable.class,
                b.nana.technology.gingester.transformers.base.transformers.map.Remove.class,
                b.nana.technology.gingester.transformers.base.transformers.map.Stream.class,
                b.nana.technology.gingester.transformers.base.transformers.object.Distinct.class,
                b.nana.technology.gingester.transformers.base.transformers.object.ToJson.class,
                b.nana.technology.gingester.transformers.base.transformers.object.ToString.class,
                b.nana.technology.gingester.transformers.base.transformers.object.ToXml.class,
                b.nana.technology.gingester.transformers.base.transformers.outputstream.Close.class,
                b.nana.technology.gingester.transformers.base.transformers.outputstream.Write.class,
                b.nana.technology.gingester.transformers.base.transformers.path.Def.class,
                b.nana.technology.gingester.transformers.base.transformers.path.Delete.class,
                b.nana.technology.gingester.transformers.base.transformers.path.FilterExistsIn.class,
                b.nana.technology.gingester.transformers.base.transformers.path.FilterExistsOut.class,
                b.nana.technology.gingester.transformers.base.transformers.path.LastModified.class,
                b.nana.technology.gingester.transformers.base.transformers.path.Link.class,
                b.nana.technology.gingester.transformers.base.transformers.path.Move.class,
                b.nana.technology.gingester.transformers.base.transformers.path.Overwrite.class,
                b.nana.technology.gingester.transformers.base.transformers.path.OverwriteSync.class,
                b.nana.technology.gingester.transformers.base.transformers.path.Search.class,
                b.nana.technology.gingester.transformers.base.transformers.path.ToInputStream.class,
                b.nana.technology.gingester.transformers.base.transformers.path.ToOutputStream.class,
                b.nana.technology.gingester.transformers.base.transformers.path.Size.class,
                b.nana.technology.gingester.transformers.base.transformers.path.Watch.class,
                b.nana.technology.gingester.transformers.base.transformers.path.Write.class,
                b.nana.technology.gingester.transformers.base.transformers.path.WriteSync.class,
                b.nana.technology.gingester.transformers.base.transformers.primitive.CountCollect.class,
                b.nana.technology.gingester.transformers.base.transformers.regex.FilterIn.class,
                b.nana.technology.gingester.transformers.base.transformers.regex.FilterOut.class,
                b.nana.technology.gingester.transformers.base.transformers.regex.Find.class,
                b.nana.technology.gingester.transformers.base.transformers.regex.Group.class,
                b.nana.technology.gingester.transformers.base.transformers.regex.Group0.class,
                b.nana.technology.gingester.transformers.base.transformers.regex.Replace.class,
                b.nana.technology.gingester.transformers.base.transformers.regex.Route.class,
                b.nana.technology.gingester.transformers.base.transformers.resource.Open.class,
                b.nana.technology.gingester.transformers.base.transformers.set.Collect.class,
                b.nana.technology.gingester.transformers.base.transformers.set.Diff.class,
                b.nana.technology.gingester.transformers.base.transformers.set.Stream.class,
                b.nana.technology.gingester.transformers.base.transformers.std.In.class,
                b.nana.technology.gingester.transformers.base.transformers.std.Out.class,
                b.nana.technology.gingester.transformers.base.transformers.string.Append.class,
                b.nana.technology.gingester.transformers.base.transformers.string.FilterEmptyIn.class,
                b.nana.technology.gingester.transformers.base.transformers.string.FilterEmptyOut.class,
                b.nana.technology.gingester.transformers.base.transformers.string.Lowercase.class,
                b.nana.technology.gingester.transformers.base.transformers.string.Split.class,
                b.nana.technology.gingester.transformers.base.transformers.string.ToBigDecimal.class,
                b.nana.technology.gingester.transformers.base.transformers.string.ToBytes.class,
                b.nana.technology.gingester.transformers.base.transformers.string.ToInputStream.class,
                b.nana.technology.gingester.transformers.base.transformers.string.ToJson.class,
                b.nana.technology.gingester.transformers.base.transformers.string.ToJsonNode.class,
                b.nana.technology.gingester.transformers.base.transformers.string.Trim.class,
                b.nana.technology.gingester.transformers.base.transformers.string.Uppercase.class,
                b.nana.technology.gingester.transformers.base.transformers.time.AsOffsetDateTime.class,
                b.nana.technology.gingester.transformers.base.transformers.time.FromMillis.class,
                b.nana.technology.gingester.transformers.base.transformers.time.FromSeconds.class,
                b.nana.technology.gingester.transformers.base.transformers.time.FromString.class,
                b.nana.technology.gingester.transformers.base.transformers.time.Now.class,
                b.nana.technology.gingester.transformers.base.transformers.time.ToString.class,
                b.nana.technology.gingester.transformers.base.transformers.util.Choke.class,
                b.nana.technology.gingester.transformers.base.transformers.util.Count.class,
                b.nana.technology.gingester.transformers.base.transformers.util.Cycle.class,
                b.nana.technology.gingester.transformers.base.transformers.util.Delay.class,
                b.nana.technology.gingester.transformers.base.transformers.util.Latch.class,
                b.nana.technology.gingester.transformers.base.transformers.util.Sample.class,
                b.nana.technology.gingester.transformers.base.transformers.util.Throttle.class,
                b.nana.technology.gingester.transformers.base.transformers.xml.FromInputStream.class,
                b.nana.technology.gingester.transformers.base.transformers.xml.ToJson.class,
                b.nana.technology.gingester.transformers.base.transformers.xml.ToObject.class,
                b.nana.technology.gingester.transformers.base.transformers.xml.XPath.class,
                b.nana.technology.gingester.transformers.base.transformers.yaml.JsonToYaml.class,
                b.nana.technology.gingester.transformers.base.transformers.yaml.ToJson.class
        );
    }
}
